### ISSUE TITLE
Add more facts

### ISSUE THREAD

**Issue by andrewkrechmer** [andrewkrechmer/Fun-Facts#2]
## TODO
*Facts left to add*
* [ ] The first computer was invented in the 1940s
* [ ] The unicorn is the national animal of Scotland
* [ ] "E" is the most common letter and appears in 11 percent of all english words
* [ ] Dolphins have been trained to be used in wars

:+1: :+1: :tada:

cc @andrewkrechmer
